// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4zbXVOcjP4aSZZ1dbMMP7g2y5ZPJyYlk',
    appId: '1:791087831841:web:bac59c7fbcc1d4fa317c60',
    messagingSenderId: '791087831841',
    projectId: 'haulistry-1b835',
    authDomain: 'haulistry-1b835.firebaseapp.com',
    storageBucket: 'haulistry-1b835.firebasestorage.app',
    measurementId: 'G-JZQ49QEWFQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAkAS9nPC6RIXOLC9G96VeRNu60b2lHLKA',
    appId: '1:791087831841:android:2243c36684a22579317c60',
    messagingSenderId: '791087831841',
    projectId: 'haulistry-1b835',
    authDomain: 'haulistry-1b835.firebaseapp.com',
    storageBucket: 'haulistry-1b835.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDu9UBQy3QJyrML2fydRL5iGQlIwcE4fhA',
    appId: '1:791087831841:ios:ea8ee65ad1e31593317c60',
    messagingSenderId: '791087831841',
    projectId: 'haulistry-1b835',
    authDomain: 'haulistry-1b835.firebaseapp.com',
    storageBucket: 'haulistry-1b835.firebasestorage.app',
    iosBundleId: 'com.haulistry.app',
  );
}
